[package]
name = "baremetaltest"
version = "0.1.0"
authors = ["Kier Davis <kierdavis@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]

